#!/bin/bash
set -x

if [ "$NAMESERVER" == "" ]; then
  export NAMESERVER=`cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}' | tr '\n' ' '`
fi

echo "Nameserver is: $NAMESERVER"
echo "********** ROOT CONFIG:"
cat /usr/local/openresty/nginx/conf/nginx.conf
echo "********** DEFAULT CONFIG:"
cat /etc/nginx/conf.d/default.conf
envsubst "\$NAMESERVER" < /etc/nginx/nginx.template.conf > /etc/nginx/conf.d/default.conf
echo "********** NEW DEFAULT CONFIG:"
cat /etc/nginx/conf.d/default.conf

exec nginx -g 'daemon off;'
